---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 020-gatekeeper
  namespace: flux-system
spec:
  timeout: 2m
  path: ./_artifacts/020-gatekeeper
  interval: 5m
  prune: true
  force: false
  sourceRef:
    name: 000-root
    kind: GitRepository
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: gatekeeper-operator-controller
    namespace: openshift-operators
