---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 021-gatekeeper-instance
  namespace: flux-system
spec:
  timeout: 2m
  path: ./_artifacts/021-gatekeeper-instance
  interval: 5m
  prune: true
  force: false
  sourceRef:
    name: 000-root
    kind: GitRepository
  dependsOn:
  - name: policy-engine-operator
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: gatekeeper-audit
    namespace: openshift-gatekeeper-system
  - apiVersion: apps/v1
    kind: Deployment
    name: gatekeeper-controller-manager
    namespace: openshift-gatekeeper-system