---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: flux-system-
  name: flux-system-2lpqj
  namespace: flux-system
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/flux.flux-system: ''
  name: flux
  namespace: flux-system
spec:
  channel: stable
  installPlanApproval: Manual
  name: flux
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: flux.v0.18.3
